### ISSUE TITLE
[cs3217-staff] Please take down this repo

### ISSUE THREAD

**Issue by louislai** [jjingrong/Bubble-Blast-Remix#1]
Hi,

We notice that this repository contains solution to past year CS3217 Problem Sets.

To keep it fair for the current batch of CS3217 students, can you please take it down / make it private. We apologise for any trouble caused!

Regards,
Louis
on behalf on CS3217 Teaching Staff

**Comment by louislai** [comment]
@jjingrong

**Comment by jjingrong** [comment]
@louislai 
Got it, will make it private
